name: libpythonpropytools-CI

on: [ push ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: instalando dependências
        run: |
          pip install pipenv
          pipenv sync -d
      - name: flake8
        run: pipenv run flake8 libpythonpropytools
      - name: test
        run: pipenv run pytest libpythonpropytools --cov=libpythonpropytools --cov-report=xml
      - uses: codecov/codecov-action@v2





